# Generated by Django 4.0 on 2021-12-31 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('serialno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serialno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=264)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=264)),
                ('slug', models.CharField(max_length=264)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('serialno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.fields.CharField, to='BlogApp.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
